require:
  - rubocop-rspec

AllCops:
  EnabledByDefault: true
  TargetRubyVersion: 3.2
  Exclude: # temporary
    - lib/main.rb
    - spec/main_spec.rb

Lint/ConstantResolution:
  Enabled: false

RSpec/FilePath:
  IgnoreMethods: true
  SpecSuffixOnly: true
RSpec/AlignRightLetBrace:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false

Style/Copyright:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/DocumentationMethod:
  Enabled: false
Style/MethodCallWithArgsParentheses:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/MethodCalledOnDoEndBlock:
  Enabled: false

Bundler/GemVersion:
  Enabled: false
Bundler/GemComment:
  Enabled: false